import * as XLSX from "xlsx-js-style";

export interface ExerciseData {
  exercise: string;
  sets: number;
  reps: string;
  load: string;
  rpe: string;
  rest: string;
  description: string;
}

export interface DayData {
  week: number;
  day: string;
  exercises: ExerciseData[];
}

export interface ParsedWorkoutData {
  programTitle: string;
  weeks: {
    weekNumber: number;
    days: DayData[];
  }[];
}

/**
 * Parse the structured data section from the workout plan markdown
 */
export function parseStructuredData(planText: string): DayData[] | null {
  try {
    // Find the STRUCTURED_DATA section
    const structuredDataMatch = planText.match(
      /##\s*STRUCTURED_DATA\s*\n\s*```json\s*\n([\s\S]*?)\n\s*```|##\s*STRUCTURED_DATA\s*\n\s*([\s\S]*?)$/i
    );

    if (!structuredDataMatch) {
      // Try without code fence - look for JSON array after STRUCTURED_DATA
      const simpleMatch = planText.match(/##\s*STRUCTURED_DATA\s*\n\s*(\[[\s\S]*)/i);
      if (simpleMatch) {
        const jsonText = extractJsonArray(simpleMatch[1].trim());
        if (jsonText) {
          const jsonData = JSON.parse(jsonText);
          return jsonData as DayData[];
        }
      }
      return null;
    }

    let jsonText = (structuredDataMatch[1] || structuredDataMatch[2] || "").trim();

    // Extract only the JSON array, removing any trailing text
    const extractedJson = extractJsonArray(jsonText);

    if (!extractedJson) {
      return null;
    }

    const parsedData = JSON.parse(extractedJson);
    return parsedData as DayData[];
  } catch (error) {
    console.error("Failed to parse structured data:", error);
    return null;
  }
}

/**
 * Extract a valid JSON array from text that may have trailing content
 */
function extractJsonArray(text: string): string | null {
  try {
    // Find the opening bracket
    const startIndex = text.indexOf("[");
    if (startIndex === -1) return null;

    // Find the matching closing bracket by counting brackets
    let bracketCount = 0;
    let inString = false;
    let escapeNext = false;

    for (let i = startIndex; i < text.length; i++) {
      const char = text[i];

      if (escapeNext) {
        escapeNext = false;
        continue;
      }

      if (char === "\\") {
        escapeNext = true;
        continue;
      }

      if (char === '"') {
        inString = !inString;
        continue;
      }

      if (!inString) {
        if (char === "[" || char === "{") {
          bracketCount++;
        } else if (char === "]" || char === "}") {
          bracketCount--;

          // When we close the outermost bracket, we're done
          if (bracketCount === 0 && char === "]") {
            return text.substring(startIndex, i + 1);
          }
        }
      }
    }

    return null;
  } catch (error) {
    console.error("Failed to extract JSON array:", error);
    return null;
  }
}

/**
 * Organize parsed data by weeks
 */
export function organizeDataByWeeks(data: DayData[]): ParsedWorkoutData["weeks"] {
  const weekMap = new Map<number, DayData[]>();

  data.forEach((day) => {
    if (!weekMap.has(day.week)) {
      weekMap.set(day.week, []);
    }
    weekMap.get(day.week)!.push(day);
  });

  return Array.from(weekMap.entries())
    .sort((a, b) => a[0] - b[0])
    .map(([weekNumber, days]) => ({
      weekNumber,
      days,
    }));
}

/**
 * Generate Excel workbook from structured workout data with FitGenie styling
 */
export function generateExcelWorkbook(structuredData: DayData[], planTitle: string): XLSX.WorkBook {
  const workbook = XLSX.utils.book_new();
  const weeks = organizeDataByWeeks(structuredData);

  // FitGenie color palette (matching the app's Tailwind colors)
  const colors = {
    slate950: "0F172A", // Dark background
    slate900: "1E293B", // Card background
    slate800: "334155", // Element background
    slate700: "475569", // Borders
    slate300: "CBD5E1", // Light text
    slate100: "F1F5F9", // Lightest text
    sky500: "0EA5E9", // Primary blue accent
    sky400: "38BDF8", // Lighter blue
    sky600: "0284C7", // Darker blue
    emerald500: "10B981", // Success/accent green
    emerald400: "34D399", // Lighter green
  };

  weeks.forEach(({ weekNumber, days }) => {
    const sheetData: any[][] = [];

    // Row 1: Program title
    sheetData.push([planTitle, "", "", "", "", "", "", ""]);

    // Row 2: Generated by FitGenie note
    sheetData.push(["🏋️ Generated by FitGenie AI", "", "", "", "", "", "", ""]);

    // Row 3: Empty spacing
    sheetData.push([]);

    // Row 4: Week banner
    sheetData.push([`Week ${weekNumber}`, "", "", "", "", "", "", ""]);

    // Row 5: Column headers
    sheetData.push([
      "Day",
      "Exercise",
      "Sets",
      "Reps",
      "Load (kg/lbs)",
      "RPE",
      "Rest",
      "Exercise Description & Form Cues",
    ]);

    // Add exercise data for each day
    days.forEach((dayData, dayIndex) => {
      if (dayData.exercises.length === 0) {
        // Rest day
        sheetData.push([
          dayData.day,
          "🛌 Rest & Recovery",
          "",
          "",
          "",
          "",
          "",
          "Use this day for active recovery, stretching, or complete rest.",
        ]);
      } else {
        dayData.exercises.forEach((exercise, exerciseIndex) => {
          sheetData.push([
            exerciseIndex === 0 ? dayData.day : "", // Only show day name on first exercise
            exercise.exercise,
            exercise.sets,
            exercise.reps,
            exercise.load,
            exercise.rpe,
            exercise.rest,
            exercise.description,
          ]);
        });
      }

      // Add empty row between days for spacing
      if (dayIndex < days.length - 1) {
        sheetData.push([]);
      }
    });

    // Create worksheet
    const worksheet = XLSX.utils.aoa_to_sheet(sheetData);

    // Set column widths (optimized for readability)
    worksheet["!cols"] = [
      { wch: 22 }, // Day
      { wch: 30 }, // Exercise
      { wch: 8 }, // Sets
      { wch: 12 }, // Reps
      { wch: 14 }, // Load
      { wch: 8 }, // RPE
      { wch: 14 }, // Rest
      { wch: 70 }, // Description - wider for overflow
    ];

    // Set row heights for better spacing
    if (!worksheet["!rows"]) worksheet["!rows"] = [];
    worksheet["!rows"][0] = { hpt: 30 }; // Title row
    worksheet["!rows"][1] = { hpt: 20 }; // Subtitle
    worksheet["!rows"][3] = { hpt: 25 }; // Week banner
    worksheet["!rows"][4] = { hpt: 35 }; // Headers

    // Apply cell formatting with FitGenie theme
    const range = XLSX.utils.decode_range(worksheet["!ref"] || "A1");

    for (let R = range.s.r; R <= range.e.r; R++) {
      for (let C = range.s.c; C <= range.e.c; C++) {
        const cellAddress = XLSX.utils.encode_cell({ r: R, c: C });
        if (!worksheet[cellAddress]) {
          worksheet[cellAddress] = { t: "s", v: "" };
        }

        // Row 1: Program title - Sky blue gradient header
        if (R === 0) {
          worksheet[cellAddress].s = {
            font: { bold: true, sz: 18, color: { rgb: "FFFFFF" } },
            fill: {
              patternType: "solid",
              fgColor: { rgb: colors.sky600 },
            },
            alignment: { horizontal: "center", vertical: "center" },
            border: {
              bottom: { style: "medium", color: { rgb: colors.sky500 } },
            },
          };
        }

        // Row 2: Generated by FitGenie - Slate gray with icon
        else if (R === 1) {
          worksheet[cellAddress].s = {
            font: { italic: true, sz: 10, color: { rgb: colors.slate300 } },
            fill: {
              patternType: "solid",
              fgColor: { rgb: colors.slate900 },
            },
            alignment: { horizontal: "center", vertical: "center" },
          };
        }

        // Row 4: Week banner - Emerald green accent
        else if (R === 3) {
          worksheet[cellAddress].s = {
            font: { bold: true, sz: 14, color: { rgb: "FFFFFF" } },
            fill: {
              patternType: "solid",
              fgColor: { rgb: colors.emerald500 },
            },
            alignment: { horizontal: "left", vertical: "center", indent: 1 },
            border: {
              top: { style: "thin", color: { rgb: colors.emerald400 } },
              bottom: { style: "thin", color: { rgb: colors.emerald400 } },
            },
          };
        }

        // Row 5: Column headers - Dark slate with sky blue accent
        else if (R === 4) {
          worksheet[cellAddress].s = {
            font: { bold: true, sz: 11, color: { rgb: colors.sky400 } },
            fill: {
              patternType: "solid",
              fgColor: { rgb: colors.slate800 },
            },
            alignment: { horizontal: "center", vertical: "center", wrapText: true },
            border: {
              top: { style: "medium", color: { rgb: colors.slate700 } },
              bottom: { style: "medium", color: { rgb: colors.slate700 } },
              left: { style: "thin", color: { rgb: colors.slate700 } },
              right: { style: "thin", color: { rgb: colors.slate700 } },
            },
          };
        }

        // Data rows: Alternating dark theme rows
        else if (R > 4) {
          const cellValue = worksheet[cellAddress].v;
          const dataRowIndex = R - 5;
          const isEvenRow = Math.floor(dataRowIndex / 1) % 2 === 0;

          // Determine if this is a rest day
          const dayCell = worksheet[XLSX.utils.encode_cell({ r: R, c: 1 })];
          const isRestDay = dayCell?.v?.toString().includes("Rest");

          // Base style for data cells
          worksheet[cellAddress].s = {
            font: {
              sz: 10,
              color: { rgb: colors.slate100 },
              bold: C === 1 && cellValue, // Bold exercise names
            },
            fill: {
              patternType: "solid",
              fgColor: {
                rgb: isRestDay
                  ? "E0F2FE" // Light sky blue for rest days
                  : isEvenRow
                  ? colors.slate900
                  : colors.slate800,
              },
            },
            alignment: {
              horizontal: C === 7 ? "left" : C === 0 ? "left" : "center",
              vertical: "top",
              wrapText: C === 7 || C === 0, // Wrap text for description and day
              indent: C === 0 || C === 7 ? 1 : 0,
            },
            border: {
              left: { style: "thin", color: { rgb: colors.slate700 } },
              right: { style: "thin", color: { rgb: colors.slate700 } },
              bottom: { style: "hair", color: { rgb: colors.slate700 } },
            },
          };

          // Day names (column A) - Special styling
          if (C === 0 && cellValue) {
            worksheet[cellAddress].s.font = {
              bold: true,
              sz: 11,
              color: { rgb: colors.emerald400 },
            };
          }

          // RPE column - Color code by intensity
          if (C === 5 && cellValue) {
            const rpeValue = parseFloat(String(cellValue));
            if (!isNaN(rpeValue)) {
              if (rpeValue >= 8) {
                worksheet[cellAddress].s.font = {
                  bold: true,
                  sz: 10,
                  color: { rgb: "FF6B6B" },
                }; // Red for high intensity
              } else if (rpeValue >= 7) {
                worksheet[cellAddress].s.font = {
                  bold: true,
                  sz: 10,
                  color: { rgb: "FFA500" },
                }; // Orange for medium
              } else {
                worksheet[cellAddress].s.font = {
                  sz: 10,
                  color: { rgb: colors.emerald400 },
                }; // Green for easy
              }
            }
          }

          // Description column - allow text to flow naturally
          if (C === 7) {
            worksheet[cellAddress].s.alignment = {
              horizontal: "left",
              vertical: "top",
              wrapText: true, // Enable text wrapping
              shrinkToFit: false, // Don't shrink text
            };
          }
        }
      }
    }

    // Merge cells for title (A1:H1)
    if (!worksheet["!merges"]) worksheet["!merges"] = [];
    worksheet["!merges"].push({ s: { r: 0, c: 0 }, e: { r: 0, c: 7 } });
    worksheet["!merges"].push({ s: { r: 1, c: 0 }, e: { r: 1, c: 7 } }); // Subtitle
    worksheet["!merges"].push({ s: { r: 3, c: 0 }, e: { r: 3, c: 7 } }); // Week banner

    // Add worksheet to workbook
    XLSX.utils.book_append_sheet(workbook, worksheet, `Week ${weekNumber}`);
  });

  return workbook;
}

/**
 * Download the Excel file
 */
export function downloadExcelFile(workbook: XLSX.WorkBook, filename: string) {
  XLSX.writeFile(workbook, filename);
}

/**
 * Main function to export workout plan to Excel
 */
export function exportWorkoutToExcel(planText: string, planTitle: string): boolean {
  try {
    const structuredData = parseStructuredData(planText);

    if (!structuredData || structuredData.length === 0) {
      console.error("No structured data found in plan");
      return false;
    }

    const workbook = generateExcelWorkbook(structuredData, planTitle);
    const fileName =
      planTitle
        .replace(/[^a-z0-9]+/gi, "-")
        .replace(/^-+|-+$/g, "")
        .toLowerCase() || "fitgenie-plan";

    downloadExcelFile(workbook, `${fileName}.xlsx`);
    return true;
  } catch (error) {
    console.error("Failed to export workout to Excel:", error);
    return false;
  }
}
